/**
 * pdfSigner.js
 * ---------------------------------------------------------------------------
 * PDF Signing Utilities
 * Adds signature blocks, metadata, and integrity hashes to PDF documents.
 * Works with any jsPDF instance generated by the SCGMEX system.
 * ---------------------------------------------------------------------------
 */

// ── Signature Block ────────────────────────────────────────────────────────

/**
 * Add a three-column signature block to the current page of a jsPDF document.
 *
 * @param {jsPDF} doc - The jsPDF document instance
 * @param {Object} options - Signature options
 * @param {Object} [options.elaboro]  - { nombre, cargo }
 * @param {Object} [options.reviso]   - { nombre, cargo }
 * @param {Object} [options.autorizo] - { nombre, cargo }
 * @param {number} [y] - Y position to start signatures (auto-calculated if omitted)
 */
export function addSignatureBlock(doc, options = {}, y = null) {
  const pageWidth = doc.internal.pageSize.getWidth();
  const pageHeight = doc.internal.pageSize.getHeight();
  const startY = y || pageHeight - 60;
  const margin = 20;
  const colWidth = (pageWidth - margin * 2) / 3;

  doc.setFontSize(8);
  doc.setTextColor(100, 100, 100);

  const roles = [
    { label: 'Elaboro', data: options.elaboro },
    { label: 'Reviso', data: options.reviso },
    { label: 'Autorizo', data: options.autorizo },
  ];

  roles.forEach((role, i) => {
    const x = margin + i * colWidth + colWidth / 2;

    // Signature line
    doc.setDrawColor(120, 120, 120);
    doc.setLineWidth(0.3);
    doc.line(x - 35, startY + 15, x + 35, startY + 15);

    // Name
    doc.setFont(undefined, 'bold');
    doc.text(
      role.data?.nombre || '________________________',
      x,
      startY + 22,
      { align: 'center' },
    );

    // Cargo
    doc.setFont(undefined, 'normal');
    doc.text(role.data?.cargo || '', x, startY + 28, { align: 'center' });

    // Role label
    doc.setFontSize(7);
    doc.setFont(undefined, 'italic');
    doc.text(role.label, x, startY + 34, { align: 'center' });
    doc.setFontSize(8);
    doc.setFont(undefined, 'normal');
  });
}

// ── Digital Signature Metadata ─────────────────────────────────────────────

/**
 * Add digital-signature / sello-digital metadata text at the bottom of the
 * current page.  The text is rendered in very small, light-grey font so it
 * does not interfere with the main content.
 *
 * @param {jsPDF} doc - The jsPDF document instance
 * @param {Object} signatureData
 * @param {string} [signatureData.selloDigital]   - Hex string of the digital seal
 * @param {string} [signatureData.cadenaOriginal] - Original chain string
 * @param {string} [signatureData.timestamp]      - ISO-8601 signing timestamp
 */
export function addDigitalSignature(doc, signatureData) {
  if (!signatureData) return;

  const pageHeight = doc.internal.pageSize.getHeight();
  let y = pageHeight - 20;

  doc.setFontSize(5);
  doc.setTextColor(150, 150, 150);
  doc.setFont(undefined, 'normal');

  if (signatureData.selloDigital) {
    const sello =
      signatureData.selloDigital.length > 80
        ? signatureData.selloDigital.substring(0, 80) + '...'
        : signatureData.selloDigital;
    doc.text(`Sello Digital: ${sello}`, 20, y);
    y += 3;
  }

  if (signatureData.cadenaOriginal) {
    const cadena =
      signatureData.cadenaOriginal.length > 80
        ? signatureData.cadenaOriginal.substring(0, 80) + '...'
        : signatureData.cadenaOriginal;
    doc.text(`Cadena Original: ${cadena}`, 20, y);
    y += 3;
  }

  if (signatureData.timestamp) {
    doc.text(`Fecha de firma: ${signatureData.timestamp}`, 20, y);
    y += 3;
  }
}

// ── PDF Metadata ───────────────────────────────────────────────────────────

/**
 * Set the PDF document properties / metadata fields.
 *
 * @param {jsPDF} doc - The jsPDF document instance
 * @param {Object} options
 * @param {string} [options.title]    - Document title
 * @param {string} [options.subject]  - Document subject
 * @param {string} [options.author]   - Document author
 * @param {string} [options.keywords] - Comma-separated keywords
 */
export function setPDFMetadata(doc, options = {}) {
  doc.setProperties({
    title: options.title || 'Reporte CONAC',
    subject: options.subject || 'Estado Financiero',
    author: options.author || 'SCGMEX',
    creator: 'SCGMEX - Sistema de Contabilidad Gubernamental de Mexico',
    keywords: options.keywords || 'CONAC, LGCG, contabilidad gubernamental',
  });
}

// ── Integrity Hash ─────────────────────────────────────────────────────────

/**
 * Generate a SHA-256 integrity hash of the PDF content.
 * **Must be called AFTER the PDF is fully generated** (all pages, tables,
 * signatures, etc.) so that the hash covers the complete document.
 *
 * @param {jsPDF} doc - The fully-generated jsPDF document
 * @returns {Promise<string>} Hex-encoded SHA-256 hash
 */
export async function generatePDFHash(doc) {
  const pdfOutput = doc.output('arraybuffer');
  const hashBuffer = await crypto.subtle.digest('SHA-256', pdfOutput);
  return Array.from(new Uint8Array(hashBuffer))
    .map((b) => b.toString(16).padStart(2, '0'))
    .join('');
}

/**
 * Add an integrity-hash footer note to the last page of the document.
 *
 * @param {jsPDF} doc  - The jsPDF document
 * @param {string} hash - Pre-computed SHA-256 hex string
 */
export function addHashFooter(doc, hash) {
  if (!hash) return;

  const pageCount = doc.getNumberOfPages();
  doc.setPage(pageCount);

  const pageWidth = doc.internal.pageSize.getWidth();
  const pageHeight = doc.internal.pageSize.getHeight();

  doc.setFontSize(5);
  doc.setTextColor(170, 170, 170);
  doc.setFont(undefined, 'normal');
  doc.text(
    `Hash de integridad: ${hash}`,
    pageWidth / 2,
    pageHeight - 4,
    { align: 'center' },
  );
}
